### ISSUE TITLE
Conflict exclusively with FocusFrameSpellBar positioning with other addons.

### ISSUE THREAD

**Issue by crossfactioninstancedpvp** [XyzKangUI/DeBuffFilter#1]
Hello, I recently installed this awesome addon to remove pointless buffs on Cata Classic that don't need to be shown on target/focus frames (rep tabard bonuses, other pointless buffs) however I've encountered an issue. I use the very outdated addon MoveIt (Dragonflight S1 was the most recent update), and whenever DebuffFilter is enabled, my FocusFrameSpellBar returns to the OG default blizzard position of beneath the focus frame, I have it in a custom spot on the screen with MoveIt. Any workaround here or fix on your end? MoveIt was completely abandoned. I also had the same issue with BetterBlizzFrames also so there may be something with this addon thats causing the FocusFrameSpellBar to be locked in the default blizzard position. Thank you. PRECOGNITO UPDATE WHEN?? You create the sickest addons man. Thank you for reading.

**Comment by XyzKangUI** [comment]
The issue you are describing is because DebuffFilter hooks into Target and Focus frame spellbar to fix the position when buffs are hidden or have different sizes etc. If you are using an other addon, that also changes the position, then I suggest your only fix to open up DebuffFilter.lua and go to line 1118 and delete FocusFrameSpellBar in this code:

```
for _, v in pairs({TargetFrameSpellBar, FocusFrameSpellBar}) do
        if v then
            hooksecurefunc(v, "SetPoint", function(self)
                if self.busy then return end
                self.busy = true
                adjustCastbar(self)
                self.busy = false
            end)
        end
    end 
```

In general I don't recommend using other addons that tend to do the same thing as DebuffFilter, to avoid such conflicts. Whatever the other better something frames addon does that you mentioned, don't use the features if it is possible to disable it.

As for Precognito, I have no idea when a public update will happen. I don't play Cataclysm nor do I have any plans to start playing it. The game seems to have lots of bugs and already in an semi abandoned state.

**Comment by crossfactioninstancedpvp** [comment]
I appreciate the reply and help. That change worked perfectly.. Regardless of whether or not you play Cata/update Precognito I appreciate the addons you've put out over the last few years, I believe you're also the creator of RougeUI. Awesome stuff man. And yeah, Cata is extremely buggy.
